version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=cinetaste_password
      - DB_NAME=cinetaste_database
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: node:20-alpine 
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  mysql:
    image: mysql:8.0
    container_name: cinetaste-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cinetaste_password
      - MYSQL_DATABASE=cinetaste_database
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcinetaste_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: