version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: go run ./cmd/api/main.go

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    command: nginx -g "daemon off;"

  mysql:
    image: mysql:8.0
    container_name: cinetaste-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cinetaste_password
      MYSQL_DATABASE: cinetaste_database
    volumes:
      - ./tmp/mysql-data:/var/lib/mysql
